"""user status

Revision ID: 45fe0c3773a6
Revises: 68862c46506d
Create Date: 2026-06-27 19:17:30.496997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45fe0c3773a6'
down_revision: Union[str, None] = '68862c46506d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
