"""user data scope

Revision ID: 57b1c9e2001e
Revises: 45fe0c3773a6
Create Date: 2026-06-27 19:23:20.015014
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57b1c9e2001e'
down_revision: Union[str, None] = '45fe0c3773a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope_branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_scope_branch_id_branches'), 'branches', ['scope_branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_scope_branch_id_branches'), type_='foreignkey')
        batch_op.drop_column('scope_branch_id')

    # ### end Alembic commands ###
