"""initial schema

Revision ID: 68862c46506d
Revises: 
Create Date: 2026-06-27 07:06:55.756416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68862c46506d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_company_id'), ['company_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('commercial_reg', sa.String(length=50), nullable=True),
    sa.Column('file_number', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('eos_day_divisor', sa.Integer(), nullable=False),
    sa.Column('eos_max_months', sa.Integer(), nullable=False),
    sa.Column('alert_lead_days', sa.Integer(), nullable=False),
    sa.Column('annual_leave_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('consumed_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumed_tokens'))
    )
    with op.batch_alter_table('consumed_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumed_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumed_tokens_jti'), ['jti'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_departments_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_departments_company_id_companies')),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_departments_manager_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_company_id'), ['company_id'], unique=False)

    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('has_expiry', sa.Boolean(), nullable=False),
    sa.Column('lead_days_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    sa.UniqueConstraint('code', name=op.f('uq_document_types_code'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('civil_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('passport_number', sa.String(length=40), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('health_insurance', sa.String(length=100), nullable=True),
    sa.Column('direct_manager_id', sa.Integer(), nullable=True),
    sa.Column('worker_type', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('attendance_mode', sa.String(length=10), nullable=False),
    sa.Column('annual_leave_balance', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_employees_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments')),
    sa.ForeignKeyConstraint(['direct_manager_id'], ['employees.id'], name=op.f('fk_employees_direct_manager_id_employees')),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_employees_license_id_licenses')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_employees_shift_id_shifts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_civil_id'), ['civil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('civil_id', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_users_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_civil_id'), ['civil_id'], unique=True)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('qr_secret', sa.String(length=64), nullable=False),
    sa.Column('kiosk_key', sa.String(length=64), nullable=True),
    sa.Column('auto_checkout_minutes', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_company_id'), ['company_id'], unique=False)

    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=True),
    sa.Column('ded_type', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deductions_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_deductions_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deductions'))
    )
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deductions_company_id'), ['company_id'], unique=False)

    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_document_templates_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates'))
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_company_id'), ['company_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('extracted_data_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_documents_company_id_companies')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_entity_id'), ['entity_id'], unique=False)

    op.create_table('employee_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employee_events_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_events_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_events_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_events'))
    )
    with op.batch_alter_table('employee_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_events_employee_id'), ['employee_id'], unique=False)

    op.create_table('gov_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_gov_logs_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_gov_logs_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gov_logs'))
    )
    with op.batch_alter_table('gov_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gov_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gov_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('license_no', sa.String(length=80), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('allowed_workers', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_licenses_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_company_id'), ['company_id'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('totals_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_runs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_runs'))
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_company_id'), ['company_id'], unique=False)

    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_permits_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_permits_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits'))
    )
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permits_company_id'), ['company_id'], unique=False)

    op.create_table('request_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('approval_chain_json', sa.JSON(), nullable=False),
    sa.Column('requires_physical_signature', sa.Boolean(), nullable=False),
    sa.Column('produces_document', sa.Boolean(), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_request_types_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_types'))
    )
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_types_company_id'), ['company_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=True),
    sa.Column('request_type_code', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_requests_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_requests_employee_id_employees')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name=op.f('fk_requests_requester_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_company_id'), ['company_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('work_days', sa.String(length=30), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shifts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_company_id'), ['company_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=30), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_tasks_assignee_user_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tasks_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_dedup_key'), ['dedup_key'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_company_id', sa.Integer(), nullable=False),
    sa.Column('to_company_id', sa.Integer(), nullable=False),
    sa.Column('transferred_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_transfers_employee_id_employees')),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], name=op.f('fk_transfers_from_company_id_companies')),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], name=op.f('fk_transfers_to_company_id_companies')),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.id'], name=op.f('fk_transfers_transferred_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perm_code', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permissions')),
    sa.UniqueConstraint('user_id', 'perm_code', name='uq_user_perm')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_appointments_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_appointments_employee_id_employees')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_appointments_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_company_id'), ['company_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('in_lat', sa.Float(), nullable=True),
    sa.Column('in_lng', sa.Float(), nullable=True),
    sa.Column('out_lat', sa.Float(), nullable=True),
    sa.Column('out_lng', sa.Float(), nullable=True),
    sa.Column('selfie_in_path', sa.String(length=400), nullable=True),
    sa.Column('selfie_out_path', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_attendance_records_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_records_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_employee_id'), ['employee_id'], unique=False)

    op.create_table('branch_supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_supervisors_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branch_supervisors_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_branch_supervisors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_supervisors')),
    sa.UniqueConstraint('branch_id', 'user_id', name='uq_branch_supervisor')
    )
    with op.batch_alter_table('branch_supervisors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_supervisors_company_id'), ['company_id'], unique=False)

    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leaves_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leaves_employee_id_employees')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_leaves_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaves'))
    )
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaves_company_id'), ['company_id'], unique=False)

    op.create_table('request_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage_label', sa.String(length=150), nullable=False),
    sa.Column('approver_role', sa.String(length=30), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_request_approvals_approver_user_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_approvals_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_approvals'))
    )
    with op.batch_alter_table('request_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_approvals_request_id'), ['request_id'], unique=False)

    op.create_table('request_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_documents_request_id_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_request_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_documents'))
    )
    with op.batch_alter_table('request_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_documents_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_documents_request_id'))

    op.drop_table('request_documents')
    with op.batch_alter_table('request_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_approvals_request_id'))

    op.drop_table('request_approvals')
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaves_company_id'))

    op.drop_table('leaves')
    with op.batch_alter_table('branch_supervisors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_supervisors_company_id'))

    op.drop_table('branch_supervisors')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_company_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_company_id'))

    op.drop_table('appointments')
    op.drop_table('user_permissions')
    op.drop_table('transfers')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_tasks_company_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_user_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_company_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_company_id'))

    op.drop_table('requests')
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_types_company_id'))

    op.drop_table('request_types')
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permits_company_id'))

    op.drop_table('permits')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_company_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_company_id'))

    op.drop_table('licenses')
    with op.batch_alter_table('gov_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gov_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_gov_logs_company_id'))

    op.drop_table('gov_logs')
    with op.batch_alter_table('employee_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_events_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_events_company_id'))

    op.drop_table('employee_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_entity_id'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_company_id'))

    op.drop_table('document_templates')
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deductions_company_id'))

    op.drop_table('deductions')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_company_id'))

    op.drop_table('branches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_civil_id'))

    op.drop_table('users')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))
        batch_op.drop_index(batch_op.f('ix_employees_civil_id'))

    op.drop_table('employees')
    op.drop_table('document_types')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_company_id'))
        batch_op.drop_index(batch_op.f('ix_departments_branch_id'))

    op.drop_table('departments')
    with op.batch_alter_table('consumed_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumed_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_consumed_tokens_expires_at'))

    op.drop_table('consumed_tokens')
    op.drop_table('companies')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_company_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
