"""gov logs (pro module)

Revision ID: 964b0b319f2d
Revises: c5a30e139290
Create Date: 2026-06-27 00:52:41.969472
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '964b0b319f2d'
down_revision: Union[str, None] = 'c5a30e139290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gov_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gov_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gov_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gov_logs_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gov_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gov_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_gov_logs_company_id'))

    op.drop_table('gov_logs')
    # ### end Alembic commands ###
