"""company file number

Revision ID: a1239b95816c
Revises: 964b0b319f2d
Create Date: 2026-06-27 00:58:50.726090
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1239b95816c'
down_revision: Union[str, None] = '964b0b319f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('file_number')

    # ### end Alembic commands ###
