"""kiosk key and consumed tokens

Revision ID: cd174af84779
Revises: 7a5fbddd5ca6
Create Date: 2026-06-25 02:56:24.467672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd174af84779'
down_revision: Union[str, None] = '7a5fbddd5ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumed_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumed_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumed_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumed_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kiosk_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('kiosk_key')

    with op.batch_alter_table('consumed_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumed_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_consumed_tokens_expires_at'))

    op.drop_table('consumed_tokens')
    # ### end Alembic commands ###
